---
- name: device type block
  block:
    - name: find Device Group by name- device type
      cisco.ise.network_device_group_info:
        ise_hostname: "{{ ise_hostname }}"
        ise_username: "{{ ise_username }}"
        ise_password: "{{ ise_password }}"
        ise_verify: "{{ ise_verify }}"
        name: "Device Type#All Device Types#{{ group_name }}"
      register: results

    - name: filter for group uid
      set_fact:
        id: "{{ results.ise_response.id }}"

    - name: delete network device group device type
      cisco.ise.network_device_group:
        ise_hostname: "{{ ise_hostname }}"
        ise_username: "{{ ise_username }}"
        ise_password: "{{ ise_password }}"
        ise_verify: "{{ ise_verify }}"
        state: absent
        id: "{{ id }}"
      register: device_type_results
  when: 'resource == "device_type"'

- name: location block
  block:
    - name: find Device Group by name- location
      cisco.ise.network_device_group_info:
        ise_hostname: "{{ ise_hostname }}"
        ise_username: "{{ ise_username }}"
        ise_password: "{{ ise_password }}"
        ise_verify: "{{ ise_verify }}"
        name: "Location#All Locations#{{ group_name }}"
      register: results

    - name: filter for group uid
      set_fact:
        id: "{{ results.ise_response.id }}"

    - name: delete network device group location
      cisco.ise.network_device_group:
        ise_hostname: "{{ ise_hostname }}"
        ise_username: "{{ ise_username }}"
        ise_password: "{{ ise_password }}"
        ise_verify: "{{ ise_verify }}"
        state: absent
        id: "{{ id }}"
      register: location_results

  when: 'resource == "location"'
