- name: Create endpoint group
  vars:
    endpoint_group_name: test_endpoint_group
  cisco.ise.endpoint_group:
    ise_hostname: "{{ ise_hostname }}"
    ise_username: "{{ ise_username }}"
    ise_password: "{{ ise_password }}"
    ise_verify: false
    state: "{{ state }}"
    description: "{{ description }}"
    name: "{{ endpoint_group_name }}"
    systemDefined: false
