---
- name: Get Token
  uri:
    url: "{{ ENVIRONMENT[ISE_ENV].ISE_API_URL_USER }}"
    method: GET
    validate_certs: no
    url_username: "{{ ISE_USERNAME }}"
    url_password: "{{ ISE_PASSWORD }}"
    status_code: 200
    headers:
      Content-Type: application/json
      Accept: application/json
      X-CSRF-TOKEN: "fetch"
  register: resp_response

- name: Query user
  uri:
    url: "{{ ENVIRONMENT[ISE_ENV].ISE_API_URL_USER }}?filter=name.EQ.{{ EID }}"
    method: GET
    validate_certs: no
    url_username: "{{ ISE_USERNAME }}"
    url_password: "{{ ISE_PASSWORD }}"
    status_code: 200
    headers:
      Content-Type: application/json
      Accept: application/json
#      X-CSRF-TOKEN: "{{ resp_response.x_csrf_token }}"
      Cookie: "{{ resp_response.cookies_string }}"
  register: resp_responses

- name: get user id
  set_fact:
    user_id: "{{ resp_responses.json.SearchResult.resources[0].id }}"

- name: change password for account
  uri:
    url: "{{ ENVIRONMENT[ISE_ENV].ISE_API_URL_USER }}/{{ user_id }}"
    method: PUT
    validate_certs: no
    url_username: "{{ ISE_USERNAME }}"
    url_password: "{{ ISE_PASSWORD }}"
    status_code: 200
    body_format: json
    body:
      InternalUser:
        password : "{{ password }}"
        changePassword : False
    headers:
      Content-Type: application/json
      Accept: application/json
      X-CSRF-TOKEN: "{{ resp_response.x_csrf_token }}"
      Cookie: "{{ resp_response.cookies_string }}"
  when: ISE_ENV == "PROD"
  register: returnBody

- name: change password for account
  uri:
    url: "{{ ENVIRONMENT[ISE_ENV].ISE_API_URL_USER }}/{{ user_id }}"
    method: PUT
    validate_certs: no
    url_username: "{{ ISE_USERNAME }}"
    url_password: "{{ ISE_PASSWORD }}"
    status_code: 200
    body_format: json
    body:
      InternalUser:
        password : "{{ password }}"
        changePassword : False
    headers:
      Content-Type: application/json
      Accept: application/json
#           X-CSRF-TOKEN: "{{ token }}"
#           Cookie: "{{ getToken.cookies_string }}"
  when: ISE_ENV == "DEV"
  register: returnBody
