---
- name: Get Token
  uri:
    url: "{{ ENVIRONMENT[ISE_ENV].ISE_API_URL_USER }}"
    method: GET
    validate_certs: no
    url_username: "{{ ISE_USERNAME }}"
    url_password: "{{ ISE_PASSWORD }}"
    status_code: 200
    headers:
      Content-Type: application/json
      Accept: application/json
      X-CSRF-TOKEN: "fetch"
  register: resp_response

- name: Create New User Account
  uri:
    url: "{{ ENVIRONMENT[ISE_ENV].ISE_API_URL_USER }}"
    method: POST
    validate_certs: no
    url_username: "{{ ISE_USERNAME }}"
    url_password: "{{ ISE_PASSWORD }}"
    status_code: 201
    body_format: json
    body:
      InternalUser:
        name: "{{ EID }}"
        enabled: true
        email: "{{ email }}"
        password: "{{ password }}"
        firstName: "{{ firstName }}"
        lastName: "{{ lastName}}"
        identityGroups: "{{ templates[groupID] }}"
        changePassword : False
        customAttributes:
          Ticket_Number: "{{ ticketNumber }}"
    headers:
      Content-Type: application/json
      Accept: application/json
      X-CSRF-TOKEN: "{{ resp_response.x_csrf_token }}"
      Cookie: "{{ resp_response.cookies_string }}"
  when: ISE_ENV == "PROD"

- name: Create New User Account
  uri:
    url: "{{ ENVIRONMENT[ISE_ENV].ISE_API_URL_USER }}"
    method: POST
    validate_certs: no
    url_username: "{{ ISE_USERNAME }}"
    url_password: "{{ ISE_PASSWORD }}"
    status_code: 201
    body_format: json
    body:
      InternalUser:
        name: "{{ EID }}"
        enabled: true
        email: "{{ email }}"
        password: "{{ password }}"
        firstName: "{{ firstName }}"
        lastName: "{{ lastName}}"
        identityGroups: "{{ templates[groupID] }}"
        changePassword : False
    headers:
      Content-Type: application/json
      Accept: application/json
      #X-CSRF-TOKEN: "{{ resp_response.x_csrf_token }}"
      Cookie: "{{ resp_response.cookies_string }}"
  when: ISE_ENV == "DEV"