- name: Get Token
  uri:
    url: "{{ ISE_API_URL }}/{{ user_id }}"
    method: GET
    validate_certs: no
    url_username: "{{ ISE_USERNAME }}"
    url_password: "{{ ISE_PASSWORD }}"
    status_code: 200
    headers:
      Content-Type: application/json
      Accept: application/json
      # X-CSRF-TOKEN: fetch
  register: getToken

#- name: Save Token
#  set_fact:
#    token: "{{ getToken.x_csrf_token }}"

- name: "Remove {{ EID }} from Privilege Group"
  uri:
    url: "{{ ISE_API_URL }}/{{ user_id }}"
    method: PUT
    validate_certs: no
    url_username: "{{ ISE_USERNAME }}"
    url_password: "{{ ISE_PASSWORD }}"
    status_code: 200
    body_format: json
    body: 
      InternalUser: 
        identityGroups: "{{ origninal_group_id }}"
    headers:
      Content-Type: application/json
      Accept: application/json
  #     X-CSRF-TOKEN: "{{ token }}"
      Cookie: "{{ getToken.cookies_string }}"
  register: returnBody

- name: Validate Group Assignment Chaged
  debug:
    msg: "{{ returnBody.json }}"
